# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/FedoseevSM"

[social.params]
icon = "brand-github"

[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://insta-stories-viewer.com/ru/hipackme/"

[[social]]
identifier = "youtube"
name = "YouTube"
url = "https://socialblade.com/youtube/handle/freelancerpotipako"

# [social.params]
# icon = "instagram"
