# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/FedoseevSM"

[social.params]
icon = "brand-github"

[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://inflact.com/instagram-viewer/?profile=hipackme"

[[social]]
identifier = "youtube"
name = "YouTube"
url = "https://inv.perditum.com/channel/UCwt4lgpwLt9kbYJhVD2k_1g"

[[social]]
identifier = "telegram"
name = "Telegram"
url = "https://t.me/semyonfedoseev"

# [social.params]
# icon = "instagram"
